### ISSUE TITLE
Upgradation of Deadbolt with security patches and Scala 3 support

### ISSUE THREAD

**Issue by atilparikh** [mkurz/deadbolt-2-java#116]
As @mkurz is about to release Play 2.9 with Scala 3 support and all, I am requesting @schaloner and @mkurz kindly consider this package upgradation.

Thanks.

**Comment by mkurz** [comment]
I will do that probably next week.

**Comment by mkurz** [comment]
All done and released, see https://github.com/mkurz/deadbolt-2-java/issues/117#issuecomment-1827953898
