### ISSUE TITLE
Support Play Framework 2.9.0

### ISSUE THREAD

**Issue by kpollardsprypoint** [mkurz/deadbolt-2-java#117]
Play Framework 2.9.0 has been released - add support.

**Comment by mkurz** [comment]
deadbolt-java 2.9.0 for Play 2.9 (akka) released, including Scala 3 artifacts:
* https://repo1.maven.org/maven2/be/objectify/deadbolt-java_2.13/2.9.0/
* https://repo1.maven.org/maven2/be/objectify/deadbolt-java_3/2.9.0/

deadbolt-java 3.0.0 for Play 3.0 (pekko) released, including Scala 3 artifacts:
* https://repo1.maven.org/maven2/be/objectify/deadbolt-java_2.13/3.0.0/
* https://repo1.maven.org/maven2/be/objectify/deadbolt-java_3/3.0.0/

The release process is now much simpler and the next release (also next major release) should be much much faster.
Thanks @kpollardsprypoint for you help!
